<a href="https://colab.research.google.com/github/Aniketpatil1992/Project/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [8]:
# Importing the dataset
data= pd.read_csv("/content/diabetes.csv.csv")
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [24]:
# Initiating variables
X = data.drop(['Outcome'], axis=1)
y = data['Outcome'].values.reshape(-1,1)


In [51]:
# Splitting data into training and testing data set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=10, random_state=10)


In [53]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [54]:
# Training our model using KNN
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [55]:
# Testing our model
y_pred = classifier.predict(X_test)

In [56]:
# Making confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[7 1]
 [1 1]]


0.8

In [57]:
#Prediction for new values
output= classifier.predict([[1,85,66,29,0,26.6,0.351,31]])
output

array([1])

In [58]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
model1 = LR.fit(X_train, y_train)
prediction1 = model1.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [59]:
# Confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, prediction1)

[[7 1]
 [1 1]]


0.7

In [60]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier()
model2 = DTC.fit(X_train, y_train)
prediction2 = model2.predict(X_test)
CM2 = confusion_matrix(y_test, prediction2)
CM2

array([[6, 2],
       [1, 1]])

In [61]:
accuracy_score(y_test,prediction2)

0.7

In [62]:
#KNN classifier
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier()
model3 = KNN.fit(X_train, y_train)
prediction3 = model3.predict(X_test)
CM3 = confusion_matrix(y_test, prediction3)
CM3

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([[7, 1],
       [1, 1]])

In [63]:
accuracy_score(y_test,prediction3)

0.8

In [64]:
#Support Vector Machine
from sklearn.svm import SVC
SVM = SVC()
model4 = SVM.fit(X_train, y_train)
prediction4 = model4.predict(X_test)
CM4 = confusion_matrix(y_test, prediction4)
CM4
accuracy_score(y_test,prediction4)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7

In [65]:
print("Accuaracy by Logistic Regression:", accuracy_score(y_test,prediction1))
print("Accuaracy by Decision Tree:", accuracy_score(y_test,prediction2))
print("Accuaracy by KNN:", accuracy_score(y_test,prediction3))
print("Accuaracy by SVM:", accuracy_score(y_test,prediction4))

Accuaracy by Logistic Regression: 0.7
Accuaracy by Decision Tree: 0.7
Accuaracy by KNN: 0.8
Accuaracy by SVM: 0.7


In [66]:
print("Enter the patient's information as given below:")
Pregnancies = int(input("Pregnancies :"))
Glucose = float(input("Glucose:"))
BloodPressure = float(input("BloodPressure:"))
SkinThickness = float(input("SkinThickness:"))
Insulin = float(input("Insulin:"))
BMI = float(input("BMI:"))
DiabetesPedigreeFunction = float(input("DiabetesPedigreeFunction:"))
Age = float(input("Age:"))
output=classifier.predict([[Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
]])
if output ==1:
    print("Patient is suffering from Diabetes")
else:
    print("Patient is not suffering from Diabetes")

Enter the patient's information as given below:
Pregnancies :1
Glucose:150
BloodPressure:140
SkinThickness:2
Insulin:2
BMI:22
DiabetesPedigreeFunction:2
Age:32
Patient is suffering from Diabetes
