<a href="https://colab.research.google.com/github/Aniketpatil1992/Project/blob/main/1st_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# improting the data set


In [2]:
data= pd.read_csv('/content/salary.csv')
data.head()


YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

Initialize the values


In [10]:
x=data['YearsExperience'].values.reshape(-1,1)
y=data['Salary'].values.reshape(-1,1)

Spliting datat set in to training and testing dataset

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)


Fitting linear regression to our training data set

In [27]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

Predection the test result

In [28]:
y_pred=reg.predict(x_test)

In [38]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9024461774180497

In [46]:
#Output result for given input
output = reg.predict([[1.5]])
output

array([[39457.30599632]])

In [47]:
#Intercept
reg.intercept_

array([25321.58301178])

In [48]:
reg.coef_

array([[9423.81532303]])

In [50]:
# Prediction for new values
experience = float(input("Enter the year of experience: "))

# Predicting salary with respect to years of experience

output = reg.predict([[experience]])
print(output)

Enter the year of experience: 4.5
[[67728.75196542]]
